# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e2e8c014ffbbc5621af4a6731ebddf"
application_url = "https://cb28-2800-484-a27c-5800-1824-2999-c17d-9909.ngrok-free.app"
embedded = true
name = "shipeu-middleware"
handle = "shipeu-middleware"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory"

  [[webhooks.subscriptions]]
  topics = [ "inventory_items/create" ]
  uri = "/webhooks/inventory"

  [[webhooks.subscriptions]]
  topics = [ "inventory_items/update" ]
  uri = "/webhooks/inventory"

  [[webhooks.subscriptions]]
  topics = [ "inventory_items/delete" ]
  uri = "/webhooks/inventory"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders,read_products,write_products,read_shipping,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_inventory,write_inventory,read_product_listings,read_customers,read_locations"

[auth]
redirect_urls = [
  "https://cb28-2800-484-a27c-5800-1824-2999-c17d-9909.ngrok-free.app/auth/callback",
  "https://cb28-2800-484-a27c-5800-1824-2999-c17d-9909.ngrok-free.app/auth/shopify/callback",
  "https://cb28-2800-484-a27c-5800-1824-2999-c17d-9909.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "wms-integration.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
